# Generated by Django 5.2.3 on 2026-09-19

import uuid
from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_code', models.CharField(max_length=64, unique=True, validators=[RegexValidator(message='Use de 3 a 64 caracteres: letras, números, hífen ou sublinhado.', regex='^[a-zA-Z0-9_-]{3,64}$')], verbose_name='atalho')),
                ('destination_url', models.URLField(max_length=2048, verbose_name='URL de destino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'link encurtado',
                'verbose_name_plural': 'links encurtados',
                'ordering': ['-created_at'],
            },
        ),
    ]
