# Generated by Django 5.2.3 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_shortenedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='destination_url',
            field=models.URLField(
                error_messages={
                    'invalid': 'Digite um endereço válido, como google.com ou https://google.com.'
                },
                max_length=2048,
                verbose_name='URL de destino',
            ),
        ),
    ]
