# Generated by Django 5.2.3 on 2026-09-19

from django.db import migrations, models


def create_shortener_quota(apps, schema_editor):
    ShortenerQuota = apps.get_model('portal', 'ShortenerQuota')
    ShortenerQuota.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_shortenedurl_destination_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenerQuota',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'trava do encurtador',
                'verbose_name_plural': 'trava do encurtador',
            },
        ),
        migrations.RunPython(create_shortener_quota, migrations.RunPython.noop),
    ]
