# Generated by Django 5.2.12 on 2026-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_feitico', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_agendamento', models.DateField()),
                ('hora_agendamento', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, default=99.9, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('pago', 'Pagamento Confirmado'), ('realizado', 'Feitico Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feitico',
                'verbose_name_plural': 'Feiticos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
