# Generated by Django 5.2.12 on 2026-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeFeitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('horarios_bloqueados', models.JSONField(blank=True, default=list, help_text='Lista de horas bloqueadas (ex: [8, 9, 10])')),
            ],
            options={
                'verbose_name': 'Disponibilidade de Feitiço',
                'verbose_name_plural': 'Disponibilidades de Feitiços',
                'ordering': ['data'],
            },
        ),
        migrations.AlterField(
            model_name='feitico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
