# Generated by Django 5.2.12 on 2026-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiticos', '0002_disponibilidadefeitico_alter_feitico_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibilidadeFeitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('dia_inteiro_indisponivel', models.BooleanField(default=False, help_text='Se marcado, o dia inteiro fica indisponível')),
                ('horas_indisponiveis', models.JSONField(blank=True, default=list, help_text='Lista de horas indisponíveis (ex: [8, 9, 10])')),
            ],
            options={
                'verbose_name': 'Indisponibilidade de Feitiço',
                'verbose_name_plural': 'Indisponibilidades de Feitiços',
                'ordering': ['data'],
            },
        ),
        migrations.DeleteModel(
            name='DisponibilidadeFeitico',
        ),
    ]
