# Generated by Django 5.2.12 on 2026-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiticos', '0003_indisponibilidadefeitico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFeitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('emoji', models.CharField(default='🔮', max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Feitiço',
                'verbose_name_plural': 'Tipos de Feitiços',
                'ordering': ['nome'],
            },
        ),
    ]
