# Generated by Django 5.2.12 on 2026-03-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiticos', '0004_tipofeitico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_produto', models.CharField(choices=[('tarot', 'Tiragem de Tarot'), ('intencao_feitico', 'Intenção de Feitiço'), ('feitico', 'Feitiço')], max_length=20)),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_agendamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('pago', 'Pagamento Confirmado'), ('aprovado', 'Aprovado (apenas para intenção)'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('token_acesso', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('intencao_relacionada', models.ForeignKey(blank=True, help_text='Intenção de feitiço relacionada (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feiticos_relacionados', to='feiticos.agendamento')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('emoji', models.CharField(default='🔮', max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarot',
                'verbose_name_plural': 'Tipos de Tarot',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Feitico',
        ),
        migrations.AlterModelOptions(
            name='indisponibilidadefeitico',
            options={'ordering': ['data'], 'verbose_name': 'Indisponibilidade', 'verbose_name_plural': 'Indisponibilidades'},
        ),
        migrations.RemoveField(
            model_name='indisponibilidadefeitico',
            name='dia_inteiro_indisponivel',
        ),
        migrations.RemoveField(
            model_name='indisponibilidadefeitico',
            name='horas_indisponiveis',
        ),
        migrations.AddField(
            model_name='indisponibilidadefeitico',
            name='indisponivel',
            field=models.BooleanField(default=False, help_text='Se marcado, este dia fica indisponível'),
        ),
    ]
