# Generated by Django 5.2.12 on 2026-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiticos', '0005_agendamento_tipotarot_delete_feitico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('pago', 'Pagamento Confirmado'), ('enviar_link', 'Enviar Link para Cliente'), ('link_enviado', 'Link Enviado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
