# Generated by Django 5.2.12 on 2026-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feiticos', '0006_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_agendamento_original',
            field=models.DateField(blank=True, help_text='Data original do agendamento (para rastreabilidade)', null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('enviar_link', 'Enviar Link para Cliente'), ('link_enviado', 'Link Enviado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_produto',
            field=models.CharField(choices=[('tarot', 'Tiragem de Tarot'), ('tarot_acompanhamento', 'Tiragem de Acompanhamento'), ('intencao_feitico', 'Intenção de Feitiço'), ('feitico', 'Feitiço')], max_length=20),
        ),
    ]
